version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false

workflows:
  version: 2
  commit:
    jobs:
      - normal_job
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - integration

jobs:
  normal_job:
    docker:
      - image: alpine
        user: root
    steps:
      - run:
          name: "Hello"
          command: echo "hello"
  integration:
    docker:
      - image: alpine
        user: root
    steps:
      - run:
          name: Hello world
          command: echo "hello world"